<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- 自定义后生成事件 -->
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
  <Exec Command="COPY &quot;$(TargetPath)&quot; &quot;$(BepResPath)&quot;" />
  <Exec Command="COPY &quot;$(TargetPath)&quot; &quot;$(PluginsPath)&quot;" />
</Target>

  <ItemGroup>
    <None Remove="ultimatetruck" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="ultimatetruck" />
  </ItemGroup>

</Project>
