<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="electricpea" />
		<None Remove="hypnosquash" />
		<None Remove="icedoomscaredyshroom" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="icedoomscaredyshroom" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CustomizeLib.MelonLoader\CustomizeLib.MelonLoader.csproj" />
	</ItemGroup>

	<ItemGroup>
	</ItemGroup>

	<ItemGroup>
		<Using Include="Il2Cpp" />
	</ItemGroup>
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="COPY &quot;$(TargetPath)&quot; &quot;..\..\res\Bepinex\Mods&quot;" />
	</Target>

</Project>
