<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="ultimatewintercabbagecannon" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="ultimatewintercabbagecannon" />
	</ItemGroup>

	<ItemGroup>
	</ItemGroup>

	<ItemGroup>
		<Using Include="Il2Cpp" />
	</ItemGroup>
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="COPY &quot;$(TargetPath)&quot; &quot;..\..\res\MelonLoader\Mods&quot;" />
		<Exec Command="COPY &quot;$(TargetPath)&quot; &quot;$(ModsPath)&quot;" />
	</Target>

</Project>
