<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<RootNamespace>UltimateMachineChomper</RootNamespace>
		<LangVersion>default</LangVersion>
		<IsPackable>false</IsPackable>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
		<NeutralLanguage>en-US</NeutralLanguage>
		<AssemblyName>UltimateMachineChomper</AssemblyName>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="ultimatemachinechomper" />
	</ItemGroup>

	<ItemGroup>

	</ItemGroup>

	<PropertyGroup>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<EnableDefaultCompileItems>false</EnableDefaultCompileItems>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="Core.cs" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="ultimatemachinechomper" />
	</ItemGroup>
	
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="COPY &quot;$(TargetPath)&quot; &quot;..\..\..\res\MelonLoader\Mods&quot;" />
	</Target>
</Project>
